resources:
- repo: self

pool:
  vmImage: 'windows-latest'
  demands: azureps

steps:
#- task: RunARMTTKTests@1
#  displayName: 'ARM TTK tests'
#  inputs:
#    templatelocation: '$(System.DefaultWorkingDirectory)\FortiGate\Active-Active-ELB-ILB'
#    resultLocation: '$(System.DefaultWorkingDirectory)\FortiGate\Active-Active-ELB-ILB'
#
#- task: PublishTestResults@2
#  displayName: 'Publish FortiGate Active/Active ELB-ILB ARM TTK results'
#  inputs:
#    testRunner: NUnit
#    testResultsFiles: '**\*-armttk.xml'
#    testRunTitle: 'FortiGate Active/Active ELB-ILB ARM TTK verification'
#  condition: always()

- task: AzurePowerShell@2
  displayName: 'Running tests: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/Active-Active-ELB-ILB/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/Active-Active-ELB-ILB'
    azurePowerShellVersion: LatestVersion

- task: PublishTestResults@2
  displayName: 'Publish ARM TTK results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\*-armttk.xml'
    testRunTitle: 'FortiGate Active/Active ELB-ILB ARM TTK verification'
  condition: always()

- task: PublishTestResults@2
  displayName: 'Publish custom test result'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'FortiGate ARM Template Active/Active ELB ILB verification'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - FortiGate/Active-Active-ELB-ILB/*.md
    include:
    - FortiGate/Active-Active-ELB-ILB/*
