resources:
- repo: self

pool:
  vmImage: 'windows-latest'
  demands: azureps

steps:
- task: AzurePowerShell@2
  displayName: 'Custom tests:'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiManager/singlefmg-single.png/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiManager/singlefmg-single.png'
    azurePowerShellVersion: LatestVersion

- task: PublishTestResults@2
  displayName: 'Publish ARM TTK results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\*-armttk.xml'
    testRunTitle: 'ARM TTK verification'
  condition: always()

- task: PublishTestResults@2
  displayName: 'Publish custom tests results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'ARM Template verification'

trigger:
  branches:
    include:
    - main
    - dev
  paths:
    exclude:
    - FortiManager/singlefmg-single.png/*.md
    include:
    - FortiManager/singlefmg-single.png/*
