resources: 
- repo: self

pool:
  vmImage: 'vs2017-win2016'
  demands: azureps

steps:
- task: AzurePowerShell@2
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/AvailabilityZones/Active-Passive-HA/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/AvailabilityZones/Active-Passive-HA'
    azurePowerShellVersion: LatestVersion


- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST-*.xml'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'FortiGate ARM Template test Active/Passive'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - FortiGate/AvailabilityZones/Active-Passive-HA/*.md 
    include:
    - FortiGate/AvailabilityZones/Active-Passive-HA/*