resources: 
- repo: self

pool:
  vmImage: 'vs2017-win2016'
  demands: azureps

steps:
- task: AzurePowerShell@2
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/Quickstart-AP-ELB-ILB/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/QuickStart-AP-ELB-ILB'
    azurePowerShellVersion: LatestVersion


- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST-*.xml'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'FortiGate ARM Template test Active/Passive'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - FortiGate/QuickStart-AP-ELB-ILB/*.md 
    include:
    - FortiGate/QuickStart-AP-ELB-ILB/*