resources:
- repo: self

pool:
  vmImage: 'vs2017-win2016'
  demands: azureps

steps:
- task: AzurePowerShell@2
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/Playground/Active-Active-Internal-1NIC/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/Playground/Active-Active-Internal-1NIC'
    azurePowerShellVersion: LatestVersion


- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST-*.xml'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'FortiGate ARM Template test 1NIC Active/Active ELB ILB'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - FortiGate/Playground/Active-Active-Internal-1NIC/*.md
    include:
    - FortiGate/Playground/Active-Active-Internal-1NIC/*
