resources:
- repo: self

pool:
  vmImage: 'vs2017-win2016'
  demands: azureps

steps:
- task: AzurePowerShell@2
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiManager/single-1nic/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiManager/single-1nic'
    azurePowerShellVersion: LatestVersion


- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST-*.xml'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'FortiGate-VM Single VM ARM Template test'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - FortiManager/single-1nic/*.md
    include:
    - FortiManager/single-1nic/*
