resources:
- repo: self

pool:
  vmImage: 'windows-latest'
  demands: azureps

steps:
- task: AzurePowerShell@2
  displayName: 'Running tests: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/AvailabilityZones/Active-Passive-ELB-ILB/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/AvailabilityZones/Active-Passive-ELB-ILB'
    azurePowerShellVersion: LatestVersion

- task: PublishTestResults@2
  displayName: 'Publish ARM TTK results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\*-armttk.xml'
    testRunTitle: 'ARM TTK verification'
  condition: always()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST-*.xml'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'ARM template and deployment test'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - FortiGate/Active-Passive-ELB-ILB/*.md
    include:
    - FortiGate/Active-Passive-ELB-ILB/*