resources:
- repo: self

pool:
  vmImage: 'vs2017-win2016'
  demands: azureps

steps:
- task: RunARMTTKTests@1
  displayName: 'ARM TTK tests'
  inputs:
    templatelocation: '$(System.DefaultWorkingDirectory)\FortiManager\single-1nic'
    resultLocation: '$(System.DefaultWorkingDirectory)\FortiManager\single-1nic'

- task: PublishTestResults@2
  displayName: 'Publish FortiGate A/P LB ARM TTK results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\*-armttk.xml'
    testRunTitle: 'FortiGate ARM TTK verification'
  condition: always()

- task: AzurePowerShell@2
  displayName: 'Custom tests: FilePath'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/Active-Passive-ELB-ILB/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/Active-Passive-ELB-ILB'
    azurePowerShellVersion: LatestVersion

- task: PublishTestResults@2
  displayName: 'Publish custom tests results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\TEST-*.xml'
    testRunTitle: 'FortiGate ARM Template test Active/Passive'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - FortiGate/Active-Passive-ELB-ILB/*.md
    include:
    - FortiGate/Active-Passive-ELB-ILB/*