name: ARM Template test Active-Active-ELB-ILB

env:
  ARMPath: FortiGate/Active-Active-ELB-ILB/

on:
  push:
    paths:
    - 'FortiGate/Active-Active-ELB-ILB/**'
    - '!FortiGate/Active-Active-ELB-ILB/**.md'

jobs:
  ARM_AA:
    name: 'ARM Template Active-Active-ELB-ILB'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Test ARM Templates - path
      id: armttktest
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: ${{ env.ARMPath }}

    - name: Test result - path
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.armttktest.outputs.results)) }}"
