name: '[FAZ] Azure Marketplace version update'

on:
  workflow_dispatch:

  schedule:
    - cron:  '00 22 * * 0'

env:
  PRODUCT: FortiAnalyzer
  PRODUCTSHORT: FAZ
  PRODUCTOFFER: fortinet-fortianalyzer
  PRODUCTSKU: fortinet-fortianalyzer

jobs:
  ARM-FAZ-Version-Update:
    name: Update FAZ version list
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login via Az module
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Verify FAZ published version, update templates when new version found
      uses: azure/powershell@v2
      with:
        inlineScript: |
          $buildingBlocks = @("single", "ha")
          $marketplaceVersions = @()
          $marketplaceVersionsUI = @()

          $marketplaceVersions = $(Get-AzVMImage -PublisherName "fortinet" -Location eastus -Offer "${env:PRODUCTOFFER}" -sku "${env:PRODUCTSKU}").Version
          [array]::Reverse($marketplaceVersions)
          $marketplaceVersions += "latest"
          $marketplaceVersions | ConvertTo-Json | Out-File -Filepath "./fazversion.json"
          $marketplaceVersions | ForEach-Object { $marketplaceVersionsUI += [pscustomobject]@{label=$_;value=$_} }
          $marketplaceVersionsUI | ConvertTo-Json | Out-File -Filepath "./fazversionui.json"

          foreach ($buildingBlock in $buildingBlocks) {
            Get-Content -Raw -Path "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json" | jq --slurpfile content "./fazversion.json" '.parameters.imageVersion.allowedValues = $content[]' | Set-Content -Path "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json"
            $content = Get-Content "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json" -Raw
            if (-Not $content -match '(?<=\r\n)\z') {
              "" | Out-File -Append "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json"
            }
            Get-Content -Raw -Path "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json" | jq --slurpfile content "./fazversionui.json" '(.parameters.basics[] | select( .name == "imageVersion" ) | .constraints.allowedValues) |= $content[]' | Set-Content -Path "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json"
            $content = Get-Content "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json" -Raw
            if (-Not $content -match '(?<=\r\n)\z') {
              "" | Out-File -Append "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json"
            }
          }
          Remove-Item "./fazversion.json"
          Remove-Item "./fazversionui.json"
        azPSVersion: "latest"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: faz-vm-update-version
        delete-branch: true
        title: '[FAZ] Azure Marketplace FAZ Version update'
        body: |
          Update report
          - Updated FortiAnalyzer version in building blocks: "single-1nic", "ha-1nic"
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        assignees: jvhoof
        reviewers: jvhoof
        draft: false
