name: '[FAZ] Azure Marketplace version update'

on:
  workflow_dispatch:

  schedule:
    - cron:  '00 22 * * 0'

env:
  PRODUCT: FortiAnalyzer
  PRODUCTSHORT: FAZ

jobs:
  ARM-FAZ-Version-Update:
    name: Update FAZ version list
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0

    - name: Azure Login via Az module
      uses: azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Verify FAZ published version, update templates when new version found
      uses: azure/powershell@v1.2.0
      with:
        inlineScript: |
          $buildingBlocks = @("single", "ha")
          $versions = @()
          $versionsui = @()

          $versions = $(Get-AzVMImage -PublisherName "fortinet" -Location eastus -Offer "fortinet-fortianalyzer" -sku "fortinet-fortianalyzer").Version
          $versions += "latest"
          $versions | ConvertTo-Json | Out-File -Filepath "./fazversion.json"
          $versions | ForEach-Object { $versionsui += [pscustomobject]@{label=$_;value=$_} }
          $versionsui | ConvertTo-Json | Out-File -Filepath "./fazversionui.json"

          foreach ($buildingBlock in $buildingBlocks) {
            Get-Content -Raw -Path "./FortiAnalyzer/${buildingBlock}/mainTemplate.json" | jq --slurpfile content "./fazversion.json" '.parameters.imageVersion.allowedValues = $content[]' | Set-Content -Path "./FortiAnalyzer/${buildingBlock}/mainTemplate.json"
            $content = Get-Content "./FortiAnalyzer/${buildingBlock}/mainTemplate.json" -Raw
            if (-Not $content -match '(?<=\r\n)\z') {
              "" | Out-File -Append "./FortiAnalyzer/${buildingBlock}/mainTemplate.json"
            }
            Get-Content -Raw -Path "./FortiAnalyzer/${buildingBlock}/createUiDefinition.json" | jq --slurpfile content "./fazversionui.json" '(.parameters.basics[] | select( .name == \"imageVersion\") | .constraints.allowedValues) |= $content[]' | Set-Content -Path "./FortiAnalyzer/${buildingBlock}/createUiDefinition.json"
            $content = Get-Content "./FortiAnalyzer/${buildingBlock}/createUiDefinition.json" -Raw
            if (-Not $content -match '(?<=\r\n)\z') {
              "" | Out-File -Append "./FortiAnalyzer/${buildingBlock}/createUiDefinition.json"
            }
          }
          Remove-Item "./fazversion.json"
          Remove-Item "./fazversionui.json"
        azPSVersion: "latest"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: faz-vm-update-version
        delete-branch: true
        title: '[FAZ] Azure Marketplace FAZ Version update'
        body: |
          Update report
          - Updated FortiAnalyzer version in building blocks: "single-1nic", "ha-1nic"
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        assignees: jvhoof
        reviewers: jvhoof
        draft: false
