name: '[FGT] ARM - Active-Active-ELB-ILB'

env:
  ARMPath: FortiGate/Active-Active-ELB-ILB/

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'FortiGate/Active-Active-ELB-ILB/*.json'
    - 'FortiGate/Active-Active-ELB-ILB/**.tests.ps1'

jobs:
  ARM_Active-Active-ELB-ILB:
    name: 'ARM Template Active-Active-ELB-ILB'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.2.0

    - name: Test ARM Templates - path
      id: armttktest
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: ${{ env.ARMPath }}

    - name: Test result - path
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.armttktest.outputs.results)) }}"

    - name: Azure Login via Az module
      uses: azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

#    - name: Generate SSH key
#      shell: bash
#      continue-on-error: true
#      run: |
#        ssh-keygen -t rsa -b 4096 -f .github/workflows/secrets/id_rsa -C "fortigate_test@40net.cloud" -N ""

    - name: Run Pester tests (pwsh)
      uses: azure/powershell@v1.2.0
      with:
        inlineScript: |
          mkdir -p /home/runner/.ssh/
          ssh-keygen -t rsa -b 4096 -f /home/runner/.ssh/id_rsa -C "fortigate_test@40net.cloud" -N '""'
          chmod 700 /home/runner/.ssh/
          chmod 400 /home/runner/.ssh/id_rsa 
          chmod 400 /home/runner/.ssh/id_rsa.pub
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -confirm:$false -Force
          $container = New-PesterContainer -Path "${{ env.ARMPath }}" -Data @{sshkey = "/home/runner/.ssh/id_rsa"; sshkeypub = "/home/runner/.ssh/id_rsa.pub"}
          $config = New-PesterConfiguration
          $config.Run.Container = $container
          $config.Run.Exit = $true
          $config.Run.PassThru = $true
          $config.TestResult.OutputFormat = "NUnitXML"
          $config.TestResult.OutputPath = "Test-Pester.XML"
          $config.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $config
        azPSVersion: "latest"

# https://github.com/FreEZer00/teams-webhook-action
    - name: Post result to Teams
      uses: freezer00/teams-webhook-action@v1.0.0
      with:
        webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
