name: '[FPA] Azure Marketplace version update'

on:
  workflow_dispatch:

  schedule:
    - cron:  '00 22 * * 0'

env:
  PRODUCT: FortiPAM
  PRODUCTSHORT: FPA
  PRODUCTOFFER: fortinet-fortipam
  PRODUCTSKU: fortinet-fpam

jobs:
  ARM-FPA-Version-Update:
    name: Update FPA version list
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write          # required for OIDC authentication with Azure

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Azure Login
      uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Verify FPA published version, update templates when new version found
      shell: pwsh
      run: |
        $buildingBlocks = @("A-Single-VM")
        $marketplaceVersions = @()
        $marketplaceVersionsUI = @()

        $marketplaceVersions = $(Get-AzVMImage -PublisherName "fortinet" -Location eastus -Offer "${env:PRODUCTOFFER}" -sku "${env:PRODUCTSKU}").Version
        $marketplaceVersions += "latest"
        [array]::Reverse($marketplaceVersions)
        $marketplaceVersions | ConvertTo-Json | Out-File -Filepath "./fpaversion.json"
        $marketplaceVersions | ForEach-Object { $marketplaceVersionsUI += [pscustomobject]@{label=$_;value=$_} }
        $marketplaceVersionsUI | ConvertTo-Json | Out-File -Filepath "./fpaversionui.json"

        foreach ($buildingBlock in $buildingBlocks) {
          Get-Content -Raw -Path "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json" | jq --slurpfile content "./fpaversion.json" '.parameters.imageVersion.allowedValues = $content[]' | Set-Content -Path "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json"
          $content = Get-Content "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json" -Raw
          if (-Not $content -match '(?<=\r\n)\z') {
            "" | Out-File -Append "./${env:PRODUCT}/${buildingBlock}/mainTemplate.json"
          }
          Get-Content -Raw -Path "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json" | jq --slurpfile content "./fpaversionui.json" '(.parameters.basics[] | select( .name == "imageVersion" ) | .constraints.allowedValues) |= $content[]' | Set-Content -Path "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json"
          $content = Get-Content "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json" -Raw
          if (-Not $content -match '(?<=\r\n)\z') {
            "" | Out-File -Append "./${env:PRODUCT}/${buildingBlock}/createUiDefinition.json"
          }
        }
        Remove-Item "./fpaversion.json"
        Remove-Item "./fpaversionui.json"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: fpa-vm-update-version
        delete-branch: true
        title: '[FPA] Azure Marketplace FPA Version update'
        body: |
          Update report
          - Updated FortiPAM version in building blocks: "A-Single-VM"
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        assignees: jvhoof
        reviewers: jvhoof
        draft: false
