name: '[FPX] Azure Marketplace version update'

on:
  workflow_dispatch:

  schedule:
    - cron:  '00 22 * * 0'

  push:
    branches: [ dev ]
    paths:
      - 'FortiProxy/**'

env:
  PRODUCT: FortiProxy
  PRODUCTSHORT: FPX


jobs:
  ARM-FPX-Version-Update:
    name: Update FPX version list
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0

    - name: Azure Login via Az module
      uses: azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Verify FPX published version, update templates when new version found
      uses: azure/powershell@v1.2.0
      with:
        inlineScript: |
          $buildingBlocks = @("A-Single-VM")
          $fpxMarketplaceVersions = @()
          $fpxMarketplaceVersionsUI = @()

          $fortiManagerVersions = Get-AzVMImage -PublisherName "fortinet" -Location eastus -Offer "fortinet-fortiproxy" -sku "fpx-vm-byol"
          $fpxMarketplaceVersions += $($fortiManagerVersions).Version
          $fpxMarketplaceVersions += "latest"
          $fpxMarketplaceVersions | ConvertTo-Json | Out-File -Filepath "./fpxversion.json"
          $fpxMarketplaceVersions | ForEach-Object { $fpxMarketplaceVersionsUI += [pscustomobject]@{label=$_;value=$_} }
          $fpxMarketplaceVersionsUI | ConvertTo-Json | Out-File -Filepath "./fpxversionui.json"

          foreach ($buildingBlock in $buildingBlocks) {
            Get-Content -Raw -Path "./FortiProxy/${buildingBlock}/mainTemplate.json" | jq --slurpfile content "./fpxversion.json" '.parameters.imageVersion.allowedValues = $content[]' | Set-Content -Path "./FortiProxy/${buildingBlock}/mainTemplate.json"
            $content = Get-Content "./FortiProxy/${buildingBlock}/mainTemplate.json" -Raw
            if (-Not $content -match '(?<=\r\n)\z') {
              "" | Out-File -Append "./FortiProxy/${buildingBlock}/mainTemplate.json"
            }
            Get-Content -Raw -Path "./FortiProxy/${buildingBlock}/createUiDefinition.json" | jq --slurpfile content "./fpxversionui.json" '(.parameters.basics[] | select( .name == \"imageVersion\") | .constraints.allowedValues) |= $content[]' | Set-Content -Path "./FortiProxy/${buildingBlock}/createUiDefinition.json"
            $content = Get-Content "./FortiProxy/${buildingBlock}/createUiDefinition.json" -Raw
            if (-Not $content -match '(?<=\r\n)\z') {
              "" | Out-File -Append "./FortiProxy/${buildingBlock}/createUiDefinition.json"
            }
          }
          Remove-Item "./fpxversion.json"
          Remove-Item "./fpxversionui.json"
        azPSVersion: "latest"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: fpx-vm-update-version
        delete-branch: true
        title: '[FPX] Azure Marketplace FPX Version update'
        body: |
          Update report
          - Updated FortiProxy version in building blocks: "A-Single-VM"
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        assignees: jvhoof
        reviewers: jvhoof
        draft: false
