name: 'Check Markdown links'

on: 
  workflow_dispatch:
  push:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.2.0

    - name: ""
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        base-branch: main
