name: 'Markdown link check'

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.2.0

    - name: Markdown link checker
      uses: ruzickap/action-my-markdown-link-checker@v1
      with:
        config_file: .github/workflows/markdown-link-checker-config.json
        verbose: true
        quiet: true
