name: 'Markdown link check'

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.2.0

    - name: Markdown link checker
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/workflows/markdown-link-checker-config.json
        use-verbose-mode: 'yes'
        use-quiet-mode: 'yes'
