name: '[FGT] TF - A-Single-VM - ValidIaC'

env:
  TFPath: FortiGate/Terraform/A-Single-VM/terraform/

on:
  workflow_dispatch:
  push:
    paths:
    - 'FortiGate/Terraform/A-Single-VM/*.tf'
    - 'FortiGate/Terraform/A-Single-VM/*.tpl'
    - 'FortiGate/Terraform/A-Single-VM/*.hcl'

jobs:
  terraform_single-vm:
    name: 'Terraform A-Single-VM'
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.2.0

    - name: Run Docker
      run: |
           docker run --rm -v ${{ github.workspace }}:/iac ghrc.io:jvhoof/validiac secure /iac/${{ env.TFPath }}
