name: '[FGT] TF - A-Single-VM - ValidIaC'

env:
  TFPath: FortiGate/Terraform/A-Single-VM/terraform/

on:
  workflow_dispatch:
  push:
    paths:
    - 'FortiGate/Terraform/A-Single-VM/*.tf'
    - 'FortiGate/Terraform/A-Single-VM/*.tpl'
    - 'FortiGate/Terraform/A-Single-VM/*.hcl'

jobs:
  container-test-job:
    name: 'Terraform A-Single-VM'
    runs-on: ubuntu-latest
    container:
      image: ghrc.io/jvhoof/validiac:main
      volumes:
        - ${{ github.workspace }}:/iac
    steps:
      - name: ValidIaC secure check
        run: secure /iac/${{ env.TFPath }}
