name: '[FGT] TF - A-Single-VM - ValidIaC'

env:
  TFPath: FortiGate/Terraform/A-Single-VM/terraform/

on:
  workflow_dispatch:
  push:
    paths:
    - 'FortiGate/Terraform/A-Single-VM/*.tf'
    - 'FortiGate/Terraform/A-Single-VM/*.tpl'
    - 'FortiGate/Terraform/A-Single-VM/*.hcl'

jobs:
  step1:
    name: 'step1'
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.2.0

    - name: Test
      shell: bash
      run: |
           pwd
           ls -la

  step2:
    name: 'step2'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jvhoof/validiac:main
      volumes:
        - ${{ github.workspace }}:/iac
    steps:
      - name: ValidIaC secure check
        run: ls -la /iac
