name: '[FGT] TF - VNET Peering'

env:
  TFPath: FortiGate/Terraform/VNET-Peering/terraform/

on:
  push:
    paths:
    - 'FortiGate/Terraform/VNET-Peering/**.tf'
    - 'FortiGate/Terraform/VNET-Peering/**.tpl'
    - 'FortiGate/Terraform/VNET-Peering/**.hcl'

jobs:
  terraform_VNETP:
    name: 'Terraform VNET-Peering-ELB-ILB'
    runs-on: ubuntu-latest
    env:
      TF_VAR_PREFIX: "FORTIQA-VNET-Peering-${{ github.run_id }}-${{ github.run_number }}"
      TF_VAR_LOCATION: "westeurope"
      TF_VAR_USERNAME: "azureuser"
      TF_VAR_PASSWORD: "${{ secrets.PASSWORD }}"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v1

    - name: "Terraform Init"
      id: init
      run: terraform init
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Validate"
      id: validate
      run: terraform validate
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Format"
      id: format
      run: terraform fmt -check -diff
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Plan"
      id: plan
      run: terraform plan -out plan.tfplan
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Show"
      id: show
      run: terraform show -json plan.tfplan
      working-directory: ${{ env.TFPath }}

    - name: "Save Plan JSON"
      run: echo '${{ steps.show.outputs.stdout }}' > plan.json # Do not change

    - name: Run infracost diff
      uses: infracost/infracost-gh-action@master
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: /scripts/ci/diff.sh # Do not change
        path: plan.json # Do not change
        show_skipped: true
